apiVersion: v1
kind: Service
metadata:
  name: earnest-press-service
spec:
  ports:
  - port: 9022
    nodePort: 32002
    targetPort: http-port
    protocol: TCP
  selector:
    app: earnest-press
  type: LoadBalancer
