apiVersion: v1
kind: Service
metadata:
  name: earnest-press-service-2
spec:
  ports:
  - port: 80
    nodePort: 32002
    targetPort: http-port
    protocol: TCP
  selector:
    app: earnest-press
  type: LoadBalancer
